# Form implementation generated from reading ui file 'ui/main_window.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QFileDialog
from PyQt6.QtCore import pyqtSlot
from PyQt6.QtGui import *
import sys

class Ui_MainWindow(object):
    
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(626, 520)
        MainWindow.setMaximumSize(QtCore.QSize(626, 520))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(626, 450))
        self.centralwidget.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.centralwidget.setLocale(QtCore.QLocale(QtCore.QLocale.Language.Nepali, QtCore.QLocale.Country.Nepal))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(70, 0, 501, 411))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(10, 10, 10, 5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")

        #Import Area
        self.label_import = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_import.setFont(font)
        self.label_import.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)
        self.label_import.setObjectName("label_import")
        self.verticalLayout_2.addWidget(self.label_import)
        self.button_import = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.button_import.setFont(font)
        self.button_import.setObjectName("button_import")
        self.verticalLayout_2.addWidget(self.button_import)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.verticalLayout_2.addItem(spacerItem)

        #Pick Area
        self.label_pick = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)   
        self.label_pick.setFont(font)
        self.label_pick.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_pick.setObjectName("label_pick")
        self.verticalLayout_2.addWidget(self.label_pick)
        self.button_pick = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.button_pick.setFont(font)
        self.button_pick.setObjectName("button_pick")
        self.verticalLayout_2.addWidget(self.button_pick)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.verticalLayout_2.addItem(spacerItem1)
        
        #Subject Area
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, 0, -1)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_subject = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.label_subject.setObjectName("label_subject")
        self.horizontalLayout.addWidget(self.label_subject)
        self.input_subject = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Kalimati")
        font.setPointSize(10)
        self.input_subject.setFont(font)
        self.input_subject.setObjectName("input_subject")
        self.horizontalLayout.addWidget(self.input_subject)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        #Message Area
        self.label_message = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_message.setFont(font)
        self.label_message.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_message.setObjectName("label_message")
        self.verticalLayout_2.addWidget(self.label_message)
        self.scrollArea = QtWidgets.QScrollArea(parent=self.verticalLayoutWidget)
        self.scrollArea.setEnabled(True)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.scrollArea.setLineWidth(1)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustIgnored)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 481, 163))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.input_message = QtWidgets.QTextEdit(parent=self.scrollAreaWidgetContents)
        self.input_message.setGeometry(QtCore.QRect(0, 0, 499, 161))
        font = QtGui.QFont()
        font.setFamily("Kalimati")
        font.setPointSize(12)
        self.input_message.setFont(font)
        self.input_message.setObjectName("input_message")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        #Send Button
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.button_send = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_send.setGeometry(QtCore.QRect(280, 420, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        self.button_send.setFont(font)
        self.button_send.setObjectName("button_send")
        MainWindow.setCentralWidget(self.centralwidget)

        #Menu
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 626, 22))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(parent=self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        self.menu_About = QtWidgets.QMenu(parent=self.menuMenu)
        self.menu_About.setObjectName("menu_About")
        MainWindow.setMenuBar(self.menubar)
        self.actionMenu = QtGui.QAction(parent=MainWindow)
        self.actionMenu.setObjectName("actionMenu")
        self.actionExit = QtGui.QAction(parent=MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionHow_To_Use = QtGui.QAction(parent=MainWindow)
        self.actionHow_To_Use.setObjectName("actionHow_To_Use")
        self.actionCreator = QtGui.QAction(parent=MainWindow)
        self.actionCreator.setObjectName("actionCreator")
        self.menu_About.addAction(self.actionHow_To_Use)
        self.menu_About.addAction(self.actionCreator)
        self.menuMenu.addAction(self.menu_About.menuAction())
        self.menuMenu.addSeparator()
        self.menuMenu.addAction(self.actionExit)
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_import.setText(_translate("MainWindow", "Import Numbers(CSV)"))
        self.button_import.setText(_translate("MainWindow", "Import"))
        self.label_pick.setText(_translate("MainWindow", "Choose Image to Send"))
        self.button_pick.setText(_translate("MainWindow", "Pick"))
        self.label_subject.setText(_translate("MainWindow", "Subject: "))
        self.input_subject.setPlaceholderText(_translate("MainWindow", "बिषय"))
        self.label_message.setText(_translate("MainWindow", "Message"))
        self.button_send.setText(_translate("MainWindow", "Send"))
        self.menuMenu.setTitle(_translate("MainWindow", "&Menu"))
        self.menu_About.setTitle(_translate("MainWindow", "&About"))
        self.actionMenu.setText(_translate("MainWindow", "Menu"))
        self.actionExit.setText(_translate("MainWindow", "&Exit"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+F4"))
        self.actionHow_To_Use.setText(_translate("MainWindow", "How To Use?"))
        self.actionCreator.setText(_translate("MainWindow", "Creator"))
        self.actionCreator.setShortcut(_translate("MainWindow", "Ctrl+K"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
